services:
  - type: web
    name: thrill-payment-worker-bot
    env: node
    plan: free
    buildCommand: npm install; npm run build
    startCommand: node start.cjs
    autoDeploy: true
    envVars:
      - key: DASHBOARD_URL
        value: https://thrill-payment-worker-bot.onrender.com
      - key: DISCORD_CLIENT_ID
        value: "1447870937214222347"
      - key: DISCORD_REDIRECT_URI
        value: https://thrill-payment-worker-bot.onrender.com/api/auth/discord/callback
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DASHBOARD_AUTH_SECRET
        sync: false
