name = "exrworker"
main = "server/worker.ts"
compatibility_date = "2026-03-31"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/public"
binding = "ASSETS"

[vars]
BACKEND_ORIGIN = "https://expertworker.onrender.com"
